### PR TITLE
Use Teritori Logo at navigation menu (Branding)

### PR DESCRIPTION
**Pull request by omniwired**

### CODE REVIEW

**Review by hthieu1110 — APPROVED** [review]

**Review by hthieu1110 — CHANGES_REQUESTED** [review]
Seems that `/logos/teritori.svg` does not exist

**Comment by omniwired** [comment]
> Seems that `/logos/teritori.svg` does not exist
It exists and is here:
https://github.com/TERITORI/ping-pub/blob/master/public/logos/teritori.svg

**Comment by hthieu1110** [comment]
ahh, sorry. my bad, I've checked in wrong repo.

**Comment by zxxma** [comment]
LGTM.

**Pull request merged**
